DECLARE 
  l_ans VARCHAR2(4);
BEGIN
  l_ans := contract_exist('NUMER_KLIENTI', 'P2001300842IN00', 'FT');
  DBMS_OUTPUT.PUT_LINE(l_ans);
  DBMS_OUTPUT.PUT_LINE('Changes made locally');
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE(SQLERRM);
    DBMS_OUTPUT.PUT_LINE(DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;
